receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: ap-southeast-1
  prometheusremotewrite:
    endpoint: "https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/ws-9fd99638-5830-4b45-a242-f05c455200c2/api/v1/remote_write"
    auth:
      authenticator: sigv4auth

extensions:
  sigv4auth:
    region: ap-southeast-1
    service: "aps"


service:
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheusremotewrite]
    traces:
      receivers: [otlp]
      exporters: [awsxray]